# Generated by Django 5.0 on 2025-10-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodel',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='title',
            field=models.CharField(choices=[('MR', 'MR'), ('MRS', 'MRS'), ('MISS', 'MISS'), ('MS', 'MS'), ('MALLAM', 'MALLAM'), ('DOC', 'DOC'), ('BARR', 'BARR'), ('PST', 'PST'), ('PROF', 'PROF'), ('ENGR', 'ENGR'), ('ALHAJI', 'ALHAJI'), ('HAJIYAH', 'HAJIYAH')], default='MR', max_length=10),
            preserve_default=False,
        ),
    ]
