# Generated by Django 5.0 on 2025-10-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0002_staffmodel_signature_staffmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='title',
            field=models.CharField(choices=[('MR', 'MR'), ('MRS', 'MRS'), ('MISS', 'MISS'), ('MS', 'MS'), ('MALLAM', 'MALLAM'), ('DOC', 'DOC'), ('BARR', 'BARR'), ('PST', 'PST'), ('PROF', 'PROF'), ('ENGR', 'ENGR'), ('ALHAJI', 'ALHAJI'), ('HAJIYAH', 'HAJIYAH')], default='MR', max_length=10),
        ),
    ]
