# Generated by Django 5.0 on 2025-10-16 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('finance', '0001_initial'),
        ('inventory', '0001_initial'),
        ('school_setting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advancesettlementmodel',
            name='advance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='inventory.purchaseadvancemodel'),
        ),
        migrations.AddField(
            model_name='advancesettlementmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensecategorymodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategorymodel'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='school_setting.sessionmodel'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='school_setting.termmodel'),
        ),
        migrations.AddField(
            model_name='feegroupmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fee_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feemastermodel',
            name='class_sections',
            field=models.ManyToManyField(blank=True, help_text='Optional: narrow down to specific sections (e.g., JSS1 A).', to='academic.classsectionmodel'),
        ),
        migrations.AddField(
            model_name='feemastermodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feemastermodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='finance.feegroupmodel'),
        ),
        migrations.AddField(
            model_name='feemastermodel',
            name='student_classes',
            field=models.ManyToManyField(help_text='Select all classes this fee structure applies to.', to='academic.classesmodel'),
        ),
        migrations.AddField(
            model_name='feemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feemodel',
            name='payment_term',
            field=models.ForeignKey(blank=True, help_text="For 'One Time' fees, specify which term it must be paid in.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.termmodel'),
        ),
        migrations.AddField(
            model_name='feemastermodel',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structures', to='finance.feemodel'),
        ),
        migrations.AddField(
            model_name='feepaymentmodel',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financesettingmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomecategorymodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='finance.incomecategorymodel'),
        ),
        migrations.AddField(
            model_name='incomemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomemodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='school_setting.sessionmodel'),
        ),
        migrations.AddField(
            model_name='incomemodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='school_setting.termmodel'),
        ),
        migrations.AddField(
            model_name='invoicegenerationjob',
            name='classes_to_invoice',
            field=models.ManyToManyField(to='academic.classesmodel'),
        ),
        migrations.AddField(
            model_name='invoicegenerationjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicegenerationjob',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_setting.sessionmodel'),
        ),
        migrations.AddField(
            model_name='invoicegenerationjob',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_setting.termmodel'),
        ),
        migrations.AddField(
            model_name='invoiceitemmodel',
            name='fee_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.feemastermodel'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_setting.sessionmodel'),
        ),
    ]
