# Generated by Django 5.0 on 2025-10-16 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_initial'),
        ('human_resource', '0001_initial'),
        ('inventory', '0001_initial'),
        ('school_setting', '0001_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='student.studentsmodel'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_setting.termmodel'),
        ),
        migrations.AddField(
            model_name='invoiceitemmodel',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.invoicemodel'),
        ),
        migrations.AddField(
            model_name='feepaymentmodel',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.invoicemodel'),
        ),
        migrations.AddField(
            model_name='purchaseadvancepaymentmodel',
            name='advance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.purchaseadvancemodel'),
        ),
        migrations.AddField(
            model_name='purchaseadvancepaymentmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_salary_advances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.sessionmodel'),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advances', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.termmodel'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.sessionmodel'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.termmodel'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='feepaymentmodel',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.schoolbankdetail'),
        ),
        migrations.AddField(
            model_name='staffbankdetail',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='staffloan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_staff_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffloan',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.sessionmodel'),
        ),
        migrations.AddField(
            model_name='staffloan',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_loans', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='staffloan',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.termmodel'),
        ),
        migrations.AddField(
            model_name='staffloanrepayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffloanrepayment',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.sessionmodel'),
        ),
        migrations.AddField(
            model_name='staffloanrepayment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_repayments', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='staffloanrepayment',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.termmodel'),
        ),
        migrations.AddField(
            model_name='studentfundingmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who recorded this funding transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='studentfundingmodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.sessionmodel'),
        ),
        migrations.AddField(
            model_name='studentfundingmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_list', to='student.studentsmodel'),
        ),
        migrations.AddField(
            model_name='studentfundingmodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.termmodel'),
        ),
        migrations.AddField(
            model_name='supplierpaymentmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierpaymentmodel',
            name='purchase_orders',
            field=models.ManyToManyField(blank=True, to='inventory.purchaseordermodel'),
        ),
        migrations.AddField(
            model_name='supplierpaymentmodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.sessionmodel'),
        ),
        migrations.AddField(
            model_name='supplierpaymentmodel',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='inventory.suppliermodel'),
        ),
        migrations.AddField(
            model_name='supplierpaymentmodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.termmodel'),
        ),
        migrations.AddField(
            model_name='termlyfeeamountmodel',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termly_amounts', to='finance.feemastermodel'),
        ),
        migrations.AddField(
            model_name='termlyfeeamountmodel',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_setting.termmodel'),
        ),
        migrations.AddIndex(
            model_name='expensecategorymodel',
            index=models.Index(fields=['is_active'], name='finance_exp_is_acti_a213e1_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategorymodel',
            index=models.Index(fields=['name'], name='finance_exp_name_7edd95_idx'),
        ),
        migrations.AddIndex(
            model_name='expensemodel',
            index=models.Index(fields=['expense_date'], name='finance_exp_expense_81af3f_idx'),
        ),
        migrations.AddIndex(
            model_name='expensemodel',
            index=models.Index(fields=['category'], name='finance_exp_categor_1a8d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='expensemodel',
            index=models.Index(fields=['session'], name='finance_exp_session_fb9100_idx'),
        ),
        migrations.AddIndex(
            model_name='expensemodel',
            index=models.Index(fields=['term'], name='finance_exp_term_id_08fa06_idx'),
        ),
        migrations.AddConstraint(
            model_name='feemastermodel',
            constraint=models.UniqueConstraint(fields=('fee', 'group'), name='unique_fee_master_combo'),
        ),
        migrations.AddIndex(
            model_name='incomecategorymodel',
            index=models.Index(fields=['is_active'], name='finance_inc_is_acti_b98728_idx'),
        ),
        migrations.AddIndex(
            model_name='incomecategorymodel',
            index=models.Index(fields=['name'], name='finance_inc_name_af2541_idx'),
        ),
        migrations.AddIndex(
            model_name='incomemodel',
            index=models.Index(fields=['income_date'], name='finance_inc_income__bbf0d8_idx'),
        ),
        migrations.AddIndex(
            model_name='incomemodel',
            index=models.Index(fields=['category'], name='finance_inc_categor_1434e3_idx'),
        ),
        migrations.AddIndex(
            model_name='incomemodel',
            index=models.Index(fields=['session'], name='finance_inc_session_7d8bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='incomemodel',
            index=models.Index(fields=['term'], name='finance_inc_term_id_9f06fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoicemodel',
            unique_together={('student', 'session', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='salaryrecord',
            unique_together={('staff', 'month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='termlyfeeamountmodel',
            unique_together={('fee_structure', 'term')},
        ),
    ]
