# Generated by Django 5.0 on 2025-10-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feemodel',
            name='occurrence',
            field=models.CharField(choices=[('termly', 'Termly'), ('annually', 'Annually'), ('one_time', 'One Time')], max_length=50),
        ),
    ]
