# Generated by Django 5.0 on 2025-11-24 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_initial'),
        ('finance', '0004_alter_feemodel_occurrence'),
        ('human_resource', '0005_staffwalletmodel'),
        ('school_setting', '0001_initial'),
        ('student', '0003_utilitymodel_studentsmodel_utilities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed', 'Fixed Amount ($)')], help_text='The type of discount (Percentage or Fixed) locked for this term.', max_length=20)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='The exact amount or percentage locked for this term.', max_digits=10)),
                ('is_protected', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Discount Application',
                'ordering': ['-session__id', 'term__order'],
            },
        ),
        migrations.CreateModel(
            name='DiscountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Staff Discount, Early Bird Discount', max_length=250, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed', 'Fixed Amount ($)')], help_text='The intended type for this discount blueprint.', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Default value (amount/percentage) for initial application setup.', max_digits=10, null=True)),
                ('occurrence', models.CharField(choices=[('quaterly', 'Quaterly'), ('annually', 'Annually'), ('one_time', 'One Time (Single Term)')], max_length=50)),
                ('is_protected', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discount Blueprint',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='StaffFundingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to='images/funding')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('pos', 'POS'), ('bank teller', 'Bank Teller'), ('bank transfer', 'Bank Transfer')], default='cash', max_length=100)),
                ('mode', models.CharField(blank=True, choices=[('offline', 'Offline'), ('online', 'Online')], default='offline', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='confirmed', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teller_number', models.CharField(blank=True, max_length=50, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('reference', models.CharField(blank=True, help_text='Unique reference for this transaction.', max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Student Funding Record',
                'verbose_name_plural': 'Student Funding Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDiscountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_discounted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student Discount Record',
            },
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='authorised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorised_expenses', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.schoolbankdetail'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='cheque_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='cheque_prepared_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='cheque_signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_expenses', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='currency',
            field=models.CharField(choices=[('naira', 'Naira (NGN)'), ('dollar', 'Dollar (USD)')], default='naira', max_length=20),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='line_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_expenses', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='vote_and_subhead',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='voucher_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='feemodel',
            name='parent_bound',
            field=models.BooleanField(default=False, help_text='Check if this fee should be charged once per Parent/Family, rather than per student.'),
        ),
        migrations.AddField(
            model_name='feemodel',
            name='required_utility',
            field=models.ForeignKey(blank=True, help_text='If set, this fee is only applied to students subscribed to this utility (e.g., Bus Fee for Transport Utility).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.utilitymodel'),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Bank Transfer'), ('dollar_pay', 'Dollar Pay'), ('others', 'Others')], default='cash', max_length=50),
        ),
        migrations.AddIndex(
            model_name='expensemodel',
            index=models.Index(fields=['voucher_number'], name='finance_exp_voucher_a65afe_idx'),
        ),
        migrations.AddField(
            model_name='discountapplicationmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discountapplicationmodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='school_setting.sessionmodel'),
        ),
        migrations.AddField(
            model_name='discountapplicationmodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='school_setting.termmodel'),
        ),
        migrations.AddField(
            model_name='discountmodel',
            name='applicable_classes',
            field=models.ManyToManyField(blank=True, help_text='Classes this discount can apply to.', related_name='applicable_classes', to='academic.classesmodel'),
        ),
        migrations.AddField(
            model_name='discountmodel',
            name='applicable_fees',
            field=models.ManyToManyField(blank=True, help_text='Fees this discount can be applied against.', to='finance.feemodel'),
        ),
        migrations.AddField(
            model_name='discountmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discountapplicationmodel',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='finance.discountmodel'),
        ),
        migrations.AddField(
            model_name='stafffundingmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who recorded this funding transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='stafffundingmodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.sessionmodel'),
        ),
        migrations.AddField(
            model_name='stafffundingmodel',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_funding_list', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='stafffundingmodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.termmodel'),
        ),
        migrations.AddField(
            model_name='studentdiscountmodel',
            name='discount_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_discounts', to='finance.discountapplicationmodel'),
        ),
        migrations.AddField(
            model_name='studentdiscountmodel',
            name='invoice_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discounts_applied', to='finance.invoiceitemmodel'),
        ),
        migrations.AddField(
            model_name='studentdiscountmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts_received', to='student.studentsmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='discountapplicationmodel',
            unique_together={('discount', 'session', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='studentdiscountmodel',
            unique_together={('student', 'discount_application', 'invoice_item')},
        ),
    ]
