# Generated by Django 5.0 on 2025-11-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_discountapplicationmodel_discountmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmodel',
            name='occurrence',
            field=models.CharField(choices=[('termly', 'Termly'), ('annually', 'Annually'), ('one_time', 'One Time (Single Term)')], max_length=50),
        ),
    ]
