# Generated by Django 5.0 on 2025-11-28 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_discountmodel_occurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.schoolbankdetail'),
        ),
    ]
