# Generated by Django 5.0 on 2025-11-28 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_feepaymentmodel_bank_account'),
        ('student', '0004_alter_studentsmodel_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitemmodel',
            name='paid_by_sibling',
            field=models.ForeignKey(blank=True, help_text='If this is a parent-bound fee paid by a sibling', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_fees_covered', to='student.studentsmodel'),
        ),
    ]
