# Generated by Django 5.0 on 2025-12-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_invoiceitemmodel_paid_by_sibling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('reverted', 'Reverted')], default='pending', max_length=20),
        ),
    ]
