# Generated by Django 5.0 on 2026-01-23 07:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_feepaymentmodel_currency_feepaymentmodel_description_and_more'),
        ('human_resource', '0005_staffwalletmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaryrecord',
            options={'ordering': ['-year', '-month', 'staff__staff_id'], 'verbose_name': 'Salary Record', 'verbose_name_plural': 'Salary Records'},
        ),
        migrations.AlterModelOptions(
            name='salarystructure',
            options={'ordering': ['-effective_from'], 'verbose_name': 'Salary Structure', 'verbose_name_plural': 'Salary Structures'},
        ),
        migrations.RenameField(
            model_name='salaryrecord',
            old_name='basic_salary',
            new_name='annual_gross_income',
        ),
        migrations.RenameField(
            model_name='salaryrecord',
            old_name='housing_allowance',
            new_name='annual_tax',
        ),
        migrations.RenameField(
            model_name='salaryrecord',
            old_name='medical_allowance',
            new_name='gross_salary',
        ),
        migrations.RenameField(
            model_name='salaryrecord',
            old_name='other_allowances',
            new_name='monthly_tax',
        ),
        migrations.RenameField(
            model_name='salaryrecord',
            old_name='pension_amount',
            new_name='net_salary',
        ),
        migrations.RenameField(
            model_name='salaryrecord',
            old_name='salary_advance_deduction',
            new_name='other_taxes',
        ),
        migrations.RenameField(
            model_name='salaryrecord',
            old_name='tax_amount',
            new_name='taxable_income',
        ),
        migrations.RenameField(
            model_name='salaryrecord',
            old_name='transport_allowance',
            new_name='total_income',
        ),
        migrations.RemoveField(
            model_name='salaryrecord',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='housing_allowance',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='medical_allowance',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='other_allowances',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='pension_rate',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='transport_allowance',
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='additional_income',
            field=models.JSONField(default=dict, help_text='Additional income items for this month'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='allowances_breakdown',
            field=models.JSONField(default=dict, help_text='Breakdown of allowances'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='annual_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='basic_components_breakdown',
            field=models.JSONField(default=dict, help_text='Breakdown of basic salary components'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salary_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='effective_tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='payment_status',
            field=models.CharField(choices=[('not_processed', 'Not Processed'), ('pending', 'Pending Payment'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid')], default='not_processed', max_length=20),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='salary_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salary_records', to='finance.salarystructure'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='statutory_deductions',
            field=models.JSONField(default=dict, help_text='Statutory deductions breakdown (Pension, NHF, etc.)'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='total_other_deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='total_reliefs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='total_statutory_deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='total_taxation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='bank_code',
            field=models.CharField(blank=True, help_text='Bank code from NUBAN API', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='beneficiary_code',
            field=models.CharField(blank=True, help_text='Beneficiary code for bank transfer', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='branch_sort_code',
            field=models.CharField(blank=True, help_text='Branch sort code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='month',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='other_deductions',
            field=models.JSONField(default=dict, help_text='Other deductions (Loans, Advances, Welfare, etc.)'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_salaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_records', to='human_resource.staffmodel'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020)]),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='human_resource.staffmodel'),
        ),
        migrations.CreateModel(
            name='SalaryRecordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('changes', models.JSONField(default=dict, help_text='What changed')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('salary_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='finance.salaryrecord')),
            ],
            options={
                'verbose_name': 'Salary Record History',
                'verbose_name_plural': 'Salary Record Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SalarySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., '2025 Tax Rules'", max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Only one setting can be active')),
                ('is_locked', models.BooleanField(default=False, help_text='Locked once used in salary processing')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('leave_allowance_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Percentage of annual basic salary for leave allowance', max_digits=5)),
                ('basic_components', models.JSONField(default=dict, help_text='Basic salary breakdown components with codes and percentages')),
                ('allowances', models.JSONField(blank=True, default=list, help_text='Additional allowances configuration')),
                ('include_leave_in_gross', models.BooleanField(default=False, help_text='Whether to include leave allowance in gross income calculation')),
                ('reliefs_exemptions', models.JSONField(blank=True, default=list, help_text='Tax reliefs and exemptions configuration')),
                ('tax_brackets', models.JSONField(default=list, help_text='Progressive tax bracket configuration')),
                ('income_items', models.JSONField(blank=True, default=list, help_text='Additional income items to display on payslip')),
                ('statutory_deductions', models.JSONField(blank=True, default=list, help_text='Statutory deductions like Pension, NHF')),
                ('other_deductions_config', models.JSONField(default=list, help_text='Other deduction items configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salary_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary Setting',
                'verbose_name_plural': 'Salary Settings',
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='salary_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salary_records', to='finance.salarysetting'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='salary_setting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='staff_structures', to='finance.salarysetting'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('staff', 'Staff'), ('volunteer', 'Volunteer')], default='staff', help_text='Select whether this bonus is for a staff member or volunteer', max_length=10)),
                ('category', models.CharField(choices=[('vol_corp', 'Vol. Corp'), ('contractors', 'Contractors'), ('staff_monthly', 'Staff Monthly Bonus'), ('transportation', 'Transportation'), ('others', 'Others')], default='others', help_text='Select the category of this bonus', max_length=20)),
                ('volunteer_name', models.CharField(blank=True, help_text="Enter volunteer name if type is 'Volunteer'", max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Bonus amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('month', models.PositiveIntegerField(editable=False, help_text='Month extracted from due date (1-12)')),
                ('year', models.PositiveIntegerField(editable=False, help_text='Year extracted from due date')),
                ('due_date', models.DateField(default=django.utils.timezone.now, help_text='Due date for payment (month and year will be extracted from this)')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', help_text='Payment status', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this bonus', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bonuses', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, help_text="Select staff member if type is 'Staff'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='human_resource.staffmodel')),
            ],
            options={
                'verbose_name': 'Bonus',
                'verbose_name_plural': 'Bonuses',
                'ordering': ['-year', '-month', '-created_at'],
                'indexes': [models.Index(fields=['year', 'month'], name='finance_bon_year_a2b68f_idx'), models.Index(fields=['type'], name='finance_bon_type_80c50d_idx'), models.Index(fields=['category'], name='finance_bon_categor_3ca3f1_idx'), models.Index(fields=['status'], name='finance_bon_status_04e779_idx')],
            },
        ),
    ]
