# Generated by Django 5.0 on 2026-02-02 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_salaryrecord_options_and_more'),
        ('human_resource', '0005_staffwalletmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafffundingmodel',
            name='refund_reason',
            field=models.CharField(blank=True, help_text='Reason for revert/refund.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stafffundingmodel',
            name='reverted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stafffundingmodel',
            name='reverted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_staff_fundings', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='studentfundingmodel',
            name='refund_reason',
            field=models.CharField(blank=True, help_text='Reason for revert/refund.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentfundingmodel',
            name='reverted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfundingmodel',
            name='reverted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_fundings', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='studentfundingmodel',
            name='wallet_type',
            field=models.CharField(choices=[('canteen', 'Canteen Wallet'), ('fee', 'Fee Wallet')], default='canteen', help_text='Which wallet this funding is for', max_length=20),
        ),
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('bank_teller', 'Bank Teller'), ('pos', 'POS'), ('wallet', 'Fee Wallet'), ('others', 'OTHERS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stafffundingmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('reverted', 'Reverted')], default='confirmed', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentfundingmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('reverted', 'Reverted')], default='confirmed', max_length=30),
        ),
    ]
