# Generated by Django 5.0 on 2025-10-16 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0003_initial'),
        ('human_resource', '0001_initial'),
        ('inventory', '0001_initial'),
        ('school_setting', '0001_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='directsalemodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_purchases', to='student.studentsmodel'),
        ),
        migrations.AddField(
            model_name='directsalemodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.termmodel'),
        ),
        migrations.AddField(
            model_name='inventoryassignmentmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryassignmentmodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_setting.sessionmodel'),
        ),
        migrations.AddField(
            model_name='inventoryassignmentmodel',
            name='student_classes',
            field=models.ManyToManyField(blank=True, to='academic.classesmodel'),
        ),
        migrations.AddField(
            model_name='inventoryassignmentmodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_setting.termmodel'),
        ),
        migrations.AddField(
            model_name='inventoryassignmentmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectiongenerationjob',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='inventory.inventoryassignmentmodel'),
        ),
        migrations.AddField(
            model_name='inventorycollectionmodel',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='inventory.inventoryassignmentmodel'),
        ),
        migrations.AddField(
            model_name='inventorycollectionmodel',
            name='collected_by_staff',
            field=models.ForeignKey(blank=True, help_text='Staff who handed over the items', null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='inventorycollectionmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_collections', to='student.studentsmodel'),
        ),
        migrations.AddField(
            model_name='inventoryreturnmodel',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='inventory.inventorycollectionmodel'),
        ),
        migrations.AddField(
            model_name='inventoryreturnmodel',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.categorymodel'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryassignmentmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inventory.itemmodel'),
        ),
        migrations.AddField(
            model_name='directsalemodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_sales', to='inventory.itemmodel'),
        ),
        migrations.AddField(
            model_name='purchaseadvanceitemmodel',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Select from inventory items or leave blank for custom item', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemmodel'),
        ),
        migrations.AddField(
            model_name='purchaseadvancemodel',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_advances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseadvancemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_advances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseadvancemodel',
            name='disbursed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_advances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseadvancemodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.sessionmodel'),
        ),
        migrations.AddField(
            model_name='purchaseadvancemodel',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='purchaseadvancemodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.termmodel'),
        ),
        migrations.AddField(
            model_name='purchaseadvanceitemmodel',
            name='advance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseadvancemodel'),
        ),
        migrations.AddField(
            model_name='purchaseorderitemmodel',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.itemmodel'),
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.sessionmodel'),
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.termmodel'),
        ),
        migrations.AddField(
            model_name='purchaseorderitemmodel',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseordermodel'),
        ),
        migrations.AddField(
            model_name='purchasereportitemmodel',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Select from inventory items if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemmodel'),
        ),
        migrations.AddField(
            model_name='purchasereportmodel',
            name='advance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='inventory.purchaseadvancemodel'),
        ),
        migrations.AddField(
            model_name='purchasereportitemmodel',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchasereportmodel'),
        ),
        migrations.AddField(
            model_name='saleitemmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.itemmodel'),
        ),
        migrations.AddField(
            model_name='salemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='salemodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentsmodel'),
        ),
        migrations.AddField(
            model_name='salemodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.sessionmodel'),
        ),
        migrations.AddField(
            model_name='salemodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.termmodel'),
        ),
        migrations.AddField(
            model_name='saleitemmodel',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.salemodel'),
        ),
        migrations.AddField(
            model_name='stockinitemmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ins', to='inventory.itemmodel'),
        ),
        migrations.AddField(
            model_name='stockinitemmodel',
            name='purchase_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchaseorderitemmodel'),
        ),
        migrations.AddField(
            model_name='stockinmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockinmodel',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchaseordermodel'),
        ),
        migrations.AddField(
            model_name='stockinmodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.sessionmodel'),
        ),
        migrations.AddField(
            model_name='stockinmodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.termmodel'),
        ),
        migrations.AddField(
            model_name='stockinitemmodel',
            name='stock_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockinmodel'),
        ),
        migrations.AddField(
            model_name='stockoutmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stk_out_cb', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockoutmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_outs', to='inventory.itemmodel'),
        ),
        migrations.AddField(
            model_name='stockoutmodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.sessionmodel'),
        ),
        migrations.AddField(
            model_name='stockoutmodel',
            name='staff_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='stockoutmodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.termmodel'),
        ),
        migrations.AddField(
            model_name='stocktransferitemmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='inventory.itemmodel'),
        ),
        migrations.AddField(
            model_name='stocktransfermodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfermodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.sessionmodel'),
        ),
        migrations.AddField(
            model_name='stocktransfermodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.termmodel'),
        ),
        migrations.AddField(
            model_name='stocktransferitemmodel',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfermodel'),
        ),
        migrations.AddField(
            model_name='suppliermodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockinmodel',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.suppliermodel'),
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.suppliermodel'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorycollectionmodel',
            unique_together={('assignment', 'student')},
        ),
        migrations.AddConstraint(
            model_name='itemmodel',
            constraint=models.UniqueConstraint(fields=('name', 'unit'), name='unique_item_name_unit'),
        ),
    ]
