# Generated by Django 5.0 on 2025-10-18 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
        ('school_setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactivitymodel',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_setting.termmodel'),
        ),
    ]
