# Generated by Django 5.0 on 2025-10-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentsmodel',
            name='excel_pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
