# Generated by Django 5.0 on 2025-11-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_parentsmodel_excel_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the utility (e.g., Boarding, Transport)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Unique code for this utility (e.g., BRD, TRN)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Utility',
                'verbose_name_plural': 'Utilities',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='studentsmodel',
            name='utilities',
            field=models.ManyToManyField(blank=True, help_text='Services the student is subscribed to (e.g., Transport, Boarding)', related_name='students', to='student.utilitymodel'),
        ),
    ]
