# Generated by Django 5.0 on 2025-11-28 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_utilitymodel_studentsmodel_utilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsmodel',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='student.parentsmodel'),
        ),
    ]
